[crypt]
filename        = crypt.py
chunked         = true
python.required = python3.13,python3.9

[hash]
filename        = hash.py
chunked         = true
python.required = python3.13,python3.9

[cipher]
filename        = cipher.py
chunked         = true
python.required = python3.13,python3.9

[encode]
filename        = encode.py
chunked         = true
python.required = python3.13,python3.9
