[admin:TA_cryptosuite]
match = /
members = TA_cryptosuite_settings, TA_cryptosuite_crypto_settings

[admin_external:TA_cryptosuite_settings]
handlertype = python
handlerfile = TA_cryptosuite_rh_settings.py
handleractions = edit, list
python.required = python3.13,python3.9
python.version = python3.9
handlerpersistentmode = true

[admin_external:TA_cryptosuite_crypto_settings]
handlertype = python
handlerfile = TA_cryptosuite_rh_crypto_settings.py
handleractions = edit, list, remove, create
python.required = python3.13,python3.9
python.version = python3.9
handlerpersistentmode = true
